from pyspark.sql.types import *

orig_source_schema = "http://vsa.roe.ac.uk/www/VVVDR5/VVVDR5_TABLE_vvvSourceSchema.html"
orig_sourcexdetection_schema = "http://vsa.roe.ac.uk/www/VVVDR5/VVVDR5_TABLE_vvvSourceXDetectionBestMatchSchema.html"

schema_joined_source_detection = StructType(
    [
                #### FROM vvvSource ####
        StructField("sourceID", LongType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("cuEventID", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("frameSetID", LongType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ra", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("dec", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("cx", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("cy", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("cz", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("htmID", LongType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("l", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("b", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("lambda", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("eta", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("priOrSec", LongType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zmyPnt", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zmyPntErr", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ymjPnt", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ymjPntErr", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jmhPnt", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jmhPntErr", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hmksPnt", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hmksPntErr", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1mks_1Pnt", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1mks_1PntErr", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2mks_2Pnt", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2mks_2PntErr", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1mh_1Pnt", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1mh_1PntErr", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2mh_2Pnt", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2mh_2PntErr", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1my_1Pnt", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1my_1PntErr", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2my_2Pnt", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2my_2PntErr", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("mergedClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("mergedClass", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("pStar", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("pGalaxy", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("pNoise", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("pSaturated", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zMjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zAperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zAperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zAperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zAperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zAperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zAperMag4Err", FloatType(), False), #f"From vvvSource; see {orig_source_schema}"),
        StructField("zGausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zEll", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zPA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zAverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zClass", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zSeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zXi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("zEta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1Mjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1AperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1AperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1AperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1AperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1AperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1AperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1Gausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1Ell", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1PA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1ErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1AverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1Class", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1ClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1ppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1SeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1Xi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_1Eta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2Mjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2AperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2AperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2AperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2AperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2AperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2AperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2Gausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2Ell", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2PA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2ErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2AverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2Class", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2ClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2ppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2SeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2Xi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("z_2Eta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yMjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yAperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yAperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yAperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yAperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yAperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yAperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yGausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yEll", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yPA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yAverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yClass", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ySeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yXi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("yEta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1Mjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1AperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1AperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1AperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1AperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1AperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1AperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1Gausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1Ell", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1PA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1ErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1AverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1Class", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1ClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1ppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1SeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1Xi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_1Eta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2Mjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2AperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2AperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2AperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2AperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2AperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2AperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2Gausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2Ell", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2PA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2ErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2AverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2Class", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2ClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2ppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2SeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2Xi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("y_2Eta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jMjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jAperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jAperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jAperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jAperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jAperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jAperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jGausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jEll", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jPA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jAverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jClass", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jSeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jXi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("jEta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1Mjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1AperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1AperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1AperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1AperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1AperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1AperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1Gausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1Ell", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1PA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1ErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1AverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1Class", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1ClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1ppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1SeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1Xi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_1Eta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2Mjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2AperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2AperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2AperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2AperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2AperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2AperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2Gausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2Ell", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2PA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2ErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2AverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2Class", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2ClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2ppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2SeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2Xi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("j_2Eta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hMjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hAperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hAperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hAperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hAperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hAperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hAperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hGausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hEll", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hPA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hAverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hClass", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hSeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hXi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("hEta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1Mjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1AperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1AperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1AperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1AperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1AperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1AperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1Gausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1Ell", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1PA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1ErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1AverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1Class", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1ClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1ppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1SeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1Xi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_1Eta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2Mjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2AperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2AperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2AperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2AperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2AperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2AperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2Gausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2Ell", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2PA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2ErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2AverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2Class", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2ClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2ppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2SeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2Xi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("h_2Eta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksMjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksAperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksAperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksAperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksAperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksAperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksAperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksGausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksEll", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksPA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksAverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksClass", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksSeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksXi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ksEta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1Mjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1AperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1AperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1AperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1AperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1AperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1AperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1Gausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1Ell", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1PA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1ErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1AverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1Class", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1ClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1ppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1SeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1Xi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_1Eta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2Mjd", DoubleType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2AperMag1", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2AperMag1Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2AperMag3", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2AperMag3Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2AperMag4", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2AperMag4Err", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2Gausig", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2Ell", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2PA", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2ErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2AverageConf", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2Class", ShortType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2ClassStat", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2ppErrBits", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2SeqNum", IntegerType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2Xi", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
        StructField("ks_2Eta", FloatType(), False), #"From vvvSource; see {orig_source_schema}"),
                    #### LIGHT CURVES ####
        StructField("hEpochMjd", ArrayType(DoubleType(), False), False), #"Modified Julian Day in selected band"), # light curves
        StructField("jEpochMjd", ArrayType(DoubleType(), False), False), #"Modified Julian Day in selected band"),
        StructField("ksEpochMjd", ArrayType(DoubleType(), False), False), #"Modified Julian Day in selected band"),
        StructField("yEpochMjd", ArrayType(DoubleType(), False), False), #"Modified Julian Day in selected band"),
        StructField("zEpochMjd", ArrayType(DoubleType(), False), False), #"Modified Julian Day in selected band"),
        StructField("hEpochAperMag1", ArrayType(FloatType(), False), False), #"Calibrated and corrected aperture magnitude 1 in selected band"),
        StructField("jEpochAperMag1", ArrayType(FloatType(), False), False), #"Calibrated and corrected aperture magnitude 1 in selected band"),
        StructField("ksEpochAperMag1", ArrayType(FloatType(), False), False), #"Calibrated and corrected aperture magnitude 1 in selected band"),
        StructField("yEpochAperMag1", ArrayType(FloatType(), False), False), #"Calibrated and corrected aperture magnitude 1 in selected band"),
        StructField("zEpochAperMag1", ArrayType(FloatType(), False), False), #"Calibrated and corrected aperture magnitude 1 in selected band"),
        StructField("hEpochAperMag1err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 1 in selected band"),
        StructField("jEpochAperMag1err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 1 in selected band"),
        StructField("ksEpochAperMag1err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 1 in selected band"),
        StructField("yEpochAperMag1err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 1 in selected band"),
        StructField("zEpochAperMag1err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 1 in selected band"),
        StructField("hEpochAperMag2", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("jEpochAperMag2", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("ksEpochAperMag2", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("yEpochAperMag2", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("zEpochAperMag2", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("hEpochAperMag2err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("jEpochAperMag2err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("ksEpochAperMag2err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("yEpochAperMag2err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("zEpochAperMag2err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("hEpochAperMag3", ArrayType(FloatType(), False), False), #"Calibrated and corrected aperture magnitude 3 in selected band"),
        StructField("jEpochAperMag3", ArrayType(FloatType(), False), False), #"Calibrated and corrected aperture magnitude 3 in selected band"),
        StructField("ksEpochAperMag3", ArrayType(FloatType(), False), False), #"Calibrated and corrected aperture magnitude 3 in selected band"),
        StructField("yEpochAperMag3", ArrayType(FloatType(), False), False), #"Calibrated and corrected aperture magnitude 3 in selected band"),
        StructField("zEpochAperMag3", ArrayType(FloatType(), False), False), #"Calibrated and corrected aperture magnitude 3 in selected band"),
        StructField("hEpochAperMag3err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("jEpochAperMag3err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("ksEpochAperMag3err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("yEpochAperMag3err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("zEpochAperMag3err", ArrayType(FloatType(), False), False), #"Error in calibrated aperture magnitude 2 in selected band"),
        StructField("hEpochErrBits", ArrayType(IntegerType(), False), False), #"processing warning/error bitwise flags in selected band"),
        StructField("jEpochErrBits", ArrayType(IntegerType(), False), False), #"processing warning/error bitwise flags in selected band"),
        StructField("ksEpochErrBits", ArrayType(IntegerType(), False), False), #"processing warning/error bitwise flags in selected band"),
        StructField("yEpochErrBits", ArrayType(IntegerType(), False), False), #"processing warning/error bitwise flags in selected band"),
        StructField("zEpochErrBits", ArrayType(IntegerType(), False), False), #"processing warning/error bitwise flags in selected band"),
        StructField("hEpochAverageConf", ArrayType(FloatType(), False), False), #"The average confidence level in the default 2 arcsec diameter aperture (aper3) in selected band"),
        StructField("jEpochAverageConf", ArrayType(FloatType(), False), False), #"The average confidence level in the default 2 arcsec diameter aperture (aper3) in selected band"),
        StructField("ksEpochAverageConf", ArrayType(FloatType(), False), False), #"The average confidence level in the default 2 arcsec diameter aperture (aper3) in selected band"),
        StructField("yEpochAverageConf", ArrayType(FloatType(), False), False), #"The average confidence level in the default 2 arcsec diameter aperture (aper3) in selected band"),
        StructField("zEpochAverageConf", ArrayType(FloatType(), False), False), #"The average confidence level in the default 2 arcsec diameter aperture (aper3) in selected band"),
        StructField("hEpochClass", ArrayType(ShortType(), False), False), #"Flag indicating most probable morphological classification in selected band"),
        StructField("jEpochClass", ArrayType(ShortType(), False), False), #"Flag indicating most probable morphological classification in selected band"),
        StructField("ksEpochClass", ArrayType(ShortType(), False), False), #"Flag indicating most probable morphological classification in selected band"),
        StructField("yEpochClass", ArrayType(ShortType(), False), False), #"Flag indicating most probable morphological classification in selected band"),
        StructField("zEpochClass", ArrayType(ShortType(), False), False), #"Flag indicating most probable morphological classification in selected band"),
        StructField("hEpochClassStat", ArrayType(FloatType(), False), False), #"N(0,1) stellarness-of-profile statistic in selected band"),
        StructField("jEpochClassStat", ArrayType(FloatType(), False), False), #"N(0,1) stellarness-of-profile statistic in selected band"),
        StructField("ksEpochClassStat", ArrayType(FloatType(), False), False), #"N(0,1) stellarness-of-profile statistic in selected band"),
        StructField("yEpochClassStat", ArrayType(FloatType(), False), False), #"N(0,1) stellarness-of-profile statistic in selected band"),
        StructField("zEpochClassStat", ArrayType(FloatType(), False), False), #"N(0,1) stellarness-of-profile statistic in selected band"),
        StructField("hEpochDeprecated", ArrayType(ByteType(), False), False), #"Code for a current (=0) or deprecated (!=0) detection in selected band"),
        StructField("jEpochDeprecated", ArrayType(ByteType(), False), False), #"Code for a current (=0) or deprecated (!=0) detection in selected band"),
        StructField("ksEpochDeprecated", ArrayType(ByteType(), False), False), #"Code for a current (=0) or deprecated (!=0) detection in selected band"),
        StructField("yEpochDeprecated", ArrayType(ByteType(), False), False), #"Code for a current (=0) or deprecated (!=0) detection in selected band"),
        StructField("zEpochDeprecated", ArrayType(ByteType(), False), False), #"Code for a current (=0) or deprecated (!=0) detection in selected band"),
        StructField("hEpochPpErrBits", ArrayType(IntegerType(), False), False), #"additional WFAU post-processing error bits in selected band"),
        StructField("jEpochPpErrBits", ArrayType(IntegerType(), False), False), #"additional WFAU post-processing error bits in selected band"),
        StructField("ksEpochPpErrBits", ArrayType(IntegerType(), False), False), #"additional WFAU post-processing error bits in selected band"),
        StructField("yEpochPpErrBits", ArrayType(IntegerType(), False), False), #"additional WFAU post-processing error bits in selected band"),
        StructField("zEpochPpErrBits", ArrayType(IntegerType(), False), False), #"additional WFAU post-processing error bits in selected band"),
        StructField("hEpochObjID", ArrayType(LongType(), False), False), #"Unique identifier for this detection or default for no detection"),
        StructField("jEpochObjID", ArrayType(LongType(), False), False), #"Unique identifier for this detection or default for no detection"),
        StructField("ksEpochObjID", ArrayType(LongType(), False), False), #"Unique identifier for this detection or default for no detection"),
        StructField("yEpochObjID", ArrayType(LongType(), False), False), #"Unique identifier for this detection or default for no detection"),
        StructField("zEpochObjID", ArrayType(LongType(), False), False), #"Unique identifier for this detection or default for no detection"),
        StructField("hEpochMultiframeID", ArrayType(LongType(), False), False), #"Array of UIDs of the relevant multiframes"),
        StructField("jEpochMultiframeID", ArrayType(LongType(), False), False), #"Array of UIDs of the relevant multiframes"),
        StructField("ksEpochMultiframeID", ArrayType(LongType(), False), False), #"Array of UIDs of the relevant multiframes"),
        StructField("yEpochMultiframeID", ArrayType(LongType(), False), False), #"Array of UIDs of the relevant multiframes"),
        StructField("zEpochMultiframeID", ArrayType(LongType(), False), False), #"Array of UIDs of the relevant multiframes"),
        StructField("hEpochExtNum", ArrayType(ByteType(), False), False), #"Array of the extension numbers of frames"),
        StructField("jEpochExtNum", ArrayType(ByteType(), False), False), #"Array of the extension numbers of frames"),
        StructField("ksEpochExtNum", ArrayType(ByteType(), False), False), #"Array of the extension numbers of frames"),
        StructField("yEpochExtNum", ArrayType(ByteType(), False), False), #"Array of the extension numbers of frames"),
        StructField("zEpochExtNum", ArrayType(ByteType(), False), False), #"Array of the extension numbers of frames"),
        StructField("hEpochSeqNum", ArrayType(IntegerType(), False), False), #"Array of running numbers of each detection" ),
        StructField("jEpochSeqNum", ArrayType(IntegerType(), False), False), #"Array of running numbers of each detection" ),
        StructField("ksEpochSeqNum", ArrayType(IntegerType(), False), False), #"Array of running numbers of each detection" ),
        StructField("yEpochSeqNum", ArrayType(IntegerType(), False), False), #"Array of running numbers of each detection" ),
        StructField("zEpochSeqNum", ArrayType(IntegerType(), False), False), #"Array of running numbers of each detection" ),
        StructField("hEpochFlag", ArrayType(ByteType(), False), False), #"Flags for potential matching problems. From {orig_sourcexdetection_schema}"),
        StructField("jEpochFlag", ArrayType(ByteType(), False), False), #"Flags for potential matching problems. From {orig_sourcexdetection_schema}"),
        StructField("ksEpochFlag", ArrayType(ByteType(), False), False), #"Flags for potential matching problems. From {orig_sourcexdetection_schema}"),
        StructField("yEpochFlag", ArrayType(ByteType(), False), False), #"Flags for potential matching problems. From {orig_sourcexdetection_schema}"),
        StructField("zEpochFlag", ArrayType(ByteType(), False), False), #"Flags for potential matching problems. From {orig_sourcexdetection_schema}"),
        StructField("hEpochModelDistSecs", ArrayType(FloatType(), False), False), #"separation from expected position given astrometric model in vvvSource variability. From {orig_sourcexdetection_schema}"),
        StructField("jEpochModelDistSecs", ArrayType(FloatType(), False), False), #"separation from expected position given astrometric model in vvvSource variability. From {orig_sourcexdetection_schema}"),
        StructField("ksEpochModelDistSecs", ArrayType(FloatType(), False), False), #"separation from expected position given astrometric model in vvvSource variability. From {orig_sourcexdetection_schema}"),
        StructField("yEpochModelDistSecs", ArrayType(FloatType(), False), False), #"separation from expected position given astrometric model in vvvSource variability. From {orig_sourcexdetection_schema}"),
        StructField("zEpochModelDistSecs", ArrayType(FloatType(), False), False), #"separation from expected position given astrometric model in vvvSource variability. From {orig_sourcexdetection_schema}"),
    ]
)
